# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('purpose', models.CharField(max_length=500)),
                ('facultyAdvisor', models.CharField(max_length=60)),
                ('isSportsClub', models.BooleanField(max_length=60)),
                ('numDaysHeld', models.IntegerField(default=0)),
                ('daysHeld', models.IntegerField(default=0)),
                ('income', models.FloatField(default=0)),
                ('motto', models.CharField(max_length=100)),
                ('meetingsNum', models.IntegerField(default=0)),
            ],
        ),
    ]
