# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubSetup', '0002_auto_20170728_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('termStart', models.DateField()),
                ('termEnd', models.DateField()),
            ],
        ),
    ]
