# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubSetup', '0004_club_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='criteria',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='meetingsNum',
            field=models.IntegerField(default=0),
        ),
    ]
