# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubSetup', '0005_auto_20170730_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='isCurrentTerm',
            field=models.BooleanField(default=False),
        ),
    ]
