# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubSetup', '0006_term_iscurrentterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentList', models.FileField(upload_to='')),
            ],
        ),
    ]
