# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubSetup', '0007_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearID', models.IntegerField(default=-1)),
                ('studentList', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='year',
        ),
        migrations.AddField(
            model_name='term',
            name='YearID',
            field=models.ForeignKey(default=-2, on_delete=django.db.models.deletion.CASCADE, to='clubSetup.AcademicYear'),
        ),
    ]
