# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 21:39
from __future__ import unicode_literals

import clubSetup.models
import datetime
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubSetup', '0008_auto_20170810_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('form', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='YearID',
        ),
        migrations.RemoveField(
            model_name='term',
            name='YearID',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='yearID',
            field=models.IntegerField(default=clubSetup.models.setYearID),
        ),
        migrations.AddField(
            model_name='term',
            name='yearID',
            field=models.ForeignKey(default=-2017, on_delete=django.db.models.deletion.CASCADE, to='clubSetup.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='studentList',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='Files/studentList'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='term',
            name='termEnd',
            field=models.DateField(default=datetime.datetime(2017, 2, 2, 0, 0)),
        ),
        migrations.AlterField(
            model_name='term',
            name='termStart',
            field=models.DateField(default=datetime.datetime(2017, 1, 1, 0, 0)),
        ),
    ]
