# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubSetup', '0009_auto_20170812_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Critera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('critreiaID', models.IntegerField(choices=[(0, 'True/False'), (1, 'Count'), (2, 'Record Up To'), (3, 'Dues Tracker')])),
                ('criteriaDefault', models.CharField(max_length=2)),
                ('criteriaTarget', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='club',
            name='criteria',
        ),
        migrations.AddField(
            model_name='critera',
            name='clubID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubSetup.Club'),
        ),
    ]
