# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubSetup', '0010_auto_20170815_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='critera',
            old_name='critreiaID',
            new_name='criteriaID',
        ),
    ]
