# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubSetup', '0014_auto_20170815_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='id',
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
