# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubrecord',
            old_name='stud',
            new_name='student',
        ),
    ]
