# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubSetup', '0011_auto_20170815_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='initalCreate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='critera',
            name='criteriaDefault',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='critera',
            name='criteriaTarget',
            field=models.CharField(max_length=8),
        ),
    ]
