# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubSetup', '0013_auto_20170815_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubSetup.Form'),
        ),
    ]
