# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubSetup', '0015_auto_20170815_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubSetup.Form'),
        ),
    ]
