# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 23:37
from __future__ import unicode_literals

import clubSetup.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubSetup', '0016_auto_20170815_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='masterFile',
            field=models.FileField(null=True, upload_to=clubSetup.models.createCustomFolder),
        ),
    ]
