# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 00:06
from __future__ import unicode_literals

import clubSetup.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubSetup', '0018_remove_club_masterfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='masterFile',
            field=models.FileField(max_length=1000, null=True, upload_to=clubSetup.models.createCustomFolder),
        ),
    ]
