# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 19:11
from __future__ import unicode_literals

import clubSetup.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubSetup', '0019_club_masterfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Critera',
            new_name='Criteria',
        ),
        migrations.AlterField(
            model_name='club',
            name='masterFile',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=clubSetup.models.createMainClubFolder),
        ),
        migrations.AlterField(
            model_name='club',
            name='meetingsNum',
            field=models.IntegerField(default=0, verbose_name='number of meetings'),
        ),
    ]
