# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubSetup', '0020_auto_20170821_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='htmlType',
            field=models.CharField(default='', max_length=20),
        ),
    ]
